# Generated by Django 5.1.6 on 2025-04-19 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workschedule",
            options={"ordering": ["day"]},
        ),
        migrations.RemoveField(
            model_name="workschedule",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="workschedule",
            name="start_time",
        ),
        migrations.AddField(
            model_name="workschedule",
            name="end_hour",
            field=models.CharField(default="17", max_length=2),
        ),
        migrations.AddField(
            model_name="workschedule",
            name="start_hour",
            field=models.CharField(default="9", max_length=2),
        ),
        migrations.AlterField(
            model_name="workschedule",
            name="day",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="workschedule",
            name="dentist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_schedules",
                to="api.dentist",
            ),
        ),
    ]
