# Generated by Django 5.1.6 on 2025-04-21 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_workschedule_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dentalimage",
            name="image_type",
        ),
        migrations.RemoveField(
            model_name="imageanalysis",
            name="analyzed_image_url",
        ),
        migrations.AddField(
            model_name="dentalimage",
            name="imageUrl",
            field=models.CharField(default="none", max_length=50),
        ),
        migrations.AddField(
            model_name="imageanalysis",
            name="analyzed_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analyzed_analyses",
                to="api.dentalimage",
            ),
        ),
        migrations.AddField(
            model_name="imageanalysis",
            name="calculus_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="imageanalysis",
            name="caries_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="imageanalysis",
            name="gingivitis_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="imageanalysis",
            name="hypodontia_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="imageanalysis",
            name="tooth_dislocation_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="imageanalysis",
            name="total_conditions",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="imageanalysis",
            name="ulcer_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="imageanalysis",
            name="original_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="original_analyses",
                to="api.dentalimage",
            ),
        ),
    ]
