# Generated by Django 5.1.6 on 2025-04-21 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_dentalimage_image_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dentalimage",
            name="imageUrl",
        ),
        migrations.RemoveField(
            model_name="imageanalysis",
            name="analyzed_image",
        ),
        migrations.RemoveField(
            model_name="imageanalysis",
            name="calculus_count",
        ),
        migrations.RemoveField(
            model_name="imageanalysis",
            name="caries_count",
        ),
        migrations.RemoveField(
            model_name="imageanalysis",
            name="gingivitis_count",
        ),
        migrations.RemoveField(
            model_name="imageanalysis",
            name="hypodontia_count",
        ),
        migrations.RemoveField(
            model_name="imageanalysis",
            name="tooth_dislocation_count",
        ),
        migrations.RemoveField(
            model_name="imageanalysis",
            name="total_conditions",
        ),
        migrations.RemoveField(
            model_name="imageanalysis",
            name="ulcer_count",
        ),
        migrations.AddField(
            model_name="dentalimage",
            name="image_type",
            field=models.CharField(default="dental", max_length=10),
        ),
        migrations.AddField(
            model_name="imageanalysis",
            name="analyzed_image_url",
            field=models.CharField(default="none", max_length=255),
        ),
        migrations.AlterField(
            model_name="imageanalysis",
            name="original_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.dentalimage"
            ),
        ),
    ]
