# Generated by Django 5.1.6 on 2025-04-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_dentalimage_imageurl_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dentalimage",
            name="image_type",
        ),
        migrations.AddField(
            model_name="dentalimage",
            name="image_url",
            field=models.CharField(default="none", max_length=255),
        ),
        migrations.AddField(
            model_name="imageanalysis",
            name="calculus_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="imageanalysis",
            name="caries_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="imageanalysis",
            name="gingivitis_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="imageanalysis",
            name="hypodontia_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="imageanalysis",
            name="tooth_discolation_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="imageanalysis",
            name="total_conditions",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="imageanalysis",
            name="ulcer_count",
            field=models.IntegerField(default=0),
        ),
    ]
