# Generated by Django 5.1.6 on 2025-04-21 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_dentalimage_image_type_dentalimage_image_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="analyzed_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="api.imageanalysis",
            ),
        ),
    ]
