# Generated by Django 5.1.6 on 2025-04-21 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_appointment_analyzed_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="treatment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pending", "Pending"),
                    ("Missing", "Missing"),
                    ("Regular Checkup", "Regular Checkup"),
                    ("Teeth Cleaning", "Teeth Cleaning"),
                    ("Toothache", "Toothache"),
                    ("Cavity/Filling", "Cavity/Filling"),
                    ("Root Canal", "Root Canal"),
                    ("Crown/Bridge Work", "Crown/Bridge Work"),
                    ("Dentures", "Dentures"),
                    ("Implants", "Implants"),
                    ("Teeth Whitening", "Teeth Whitening"),
                    ("Orthodontic Consultation", "Orthodontic Consultation"),
                    ("Wisdom Teeth", "Wisdom Teeth"),
                    ("Gum Disease Treatment", "Gum Disease Treatment"),
                    ("Other", "Other"),
                ],
                default="Pending",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="api.patient",
            ),
        ),
    ]
