# Generated by Django 5.1.6 on 2025-04-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_appointment_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture_url",
            field=models.CharField(default="none", max_length=255),
        ),
    ]
