# Generated by Django 5.1.6 on 2025-04-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_user_profile_picture_user_profile_picture_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture_url",
            field=models.CharField(
                default="/media/profile_pictures/default.jpg", max_length=255
            ),
        ),
    ]
