# Generated by Django 5.1.6 on 2025-04-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_user_profile_picture_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageanalysis",
            name="cavity_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="imageanalysis",
            name="fillings_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="imageanalysis",
            name="impacted_tooth_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="imageanalysis",
            name="implant_count",
            field=models.IntegerField(default=0),
        ),
    ]
