# Generated by Django 5.1.6 on 2025-04-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_imageanalysis_cavity_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageanalysis",
            name="image_type",
            field=models.CharField(
                choices=[("normal", "Normal"), ("xray", "X-ray")],
                default="normal",
                max_length=10,
            ),
        ),
    ]
